apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: web
    context: ./web
    docker:
      dockerfile: Dockerfile
  - image: api
    context: ./api
    docker:
      dockerfile: Dockerfile
  - image: location
    context: ./location
    docker:
      dockerfile: Dockerfile
  - image: api-db-mig 
    context: ./migrations
    docker:
      dockerfile: Dockerfile.dev
  - image: locationmock
    context: ./devops/rumpel
    docker:
      dockerfile: Dockerfile
  - image: jobs-cleaner
    context: ./devops/jobs-cleaner
    docker:
      dockerfile: Dockerfile
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - ./devops/k8s/*.yaml
      - ./devops/k8s/rumpel-mocker/*
