apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: location
    context: ./location
    docker:
      dockerfile: Dockerfile
  - image: api-db-mig 
    context: ./migrations
    docker:
      dockerfile: Dockerfile.dev
  - image: jobs-cleaner
    context: ./devops/jobs-cleaner
    docker:
      dockerfile: Dockerfile
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - ./devops/k8s/*.yaml
      - ./devops/k8s/local-only-deps/*
