apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
    - name: "api"
      port: 1337
      targetPort: 1337
  type: LoadBalancer
  selector:
    app: api
status:
  loadBalancer: {}
