apiVersion: batch/v1
kind: Job # <-- job that runs db migrations (only one instance will run regardless of number of api instances...)
metadata:
  name: api-db-mig
spec:
  ttlSecondsAfterFinished: 10 # removes finished job after 10 seconds
  template:
    spec:
      containers:
      - name: api-db-mig
        image: api-db-mig
      restartPolicy: Never
  backoffLimit: 10